import { check } from "express-validator";

export const toothReportCustomValidation = [
  check("upperJaw.leftSide.centralIncisor").notEmpty().isString(),
  check("upperJaw.leftSide.lateralIncisor").notEmpty().isString(),
  check("upperJaw.leftSide.canine").notEmpty().isString(),
  check("upperJaw.leftSide.firstPremolar").notEmpty().isString(),
  check("upperJaw.leftSide.secondPremolar").notEmpty().isString(),
  check("upperJaw.leftSide.firstMolar").notEmpty().isString(),
  check("upperJaw.leftSide.secondMolar").notEmpty().isString(),
  check("upperJaw.leftSide.wisdomTooth").notEmpty().isString(),
  check("upperJaw.rightSide.centralIncisor").notEmpty().isString(),
  check("upperJaw.rightSide.lateralIncisor").notEmpty().isString(),
  check("upperJaw.rightSide.canine").notEmpty().isString(),
  check("upperJaw.rightSide.firstPremolar").notEmpty().isString(),
  check("upperJaw.rightSide.secondPremolar").notEmpty().isString(),
  check("upperJaw.rightSide.firstMolar").notEmpty().isString(),
  check("upperJaw.rightSide.secondMolar").notEmpty().isString(),
  check("upperJaw.rightSide.wisdomTooth").notEmpty().isString(),
  check("lowerJaw.leftSide.centralIncisor").notEmpty().isString(),
  check("lowerJaw.leftSide.lateralIncisor").notEmpty(),
  check("lowerJaw.leftSide.canine").notEmpty().isString(),
  check("lowerJaw.leftSide.firstPremolar").notEmpty().isString(),
  check("lowerJaw.leftSide.secondPremolar").notEmpty().isString(),
  check("lowerJaw.leftSide.firstMolar").notEmpty().isString(),
  check("lowerJaw.leftSide.secondMolar").notEmpty().isString(),
  check("lowerJaw.leftSide.wisdomTooth").notEmpty().isString(),
  check("lowerJaw.rightSide.centralIncisor").notEmpty().isString(),
  check("lowerJaw.rightSide.lateralIncisor").notEmpty().isString(),
  check("lowerJaw.rightSide.canine").notEmpty().isString(),
  check("lowerJaw.rightSide.firstPremolar").notEmpty().isString(),
  check("lowerJaw.rightSide.secondPremolar").notEmpty().isString(),
  check("lowerJaw.rightSide.firstMolar").notEmpty().isString(),
  check("lowerJaw.rightSide.secondMolar").notEmpty().isString(),
  check("lowerJaw.rightSide.wisdomTooth").notEmpty().isString(),
];
